book-site/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using book_site.Data.Interfaces;
using book_site.Data.Models;
using book_site.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace book_site.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly IReviews _reviews;
        private readonly UserManager<User> _userManager;

        public ReviewsController(IReviews reviews, UserManager<User> userManager)
        {
            _reviews = reviews;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            List <ReviewsViewModel> obj = _reviews.GetAllReviews.Select(r => new ReviewsViewModel
            {
                Id = r.Id,
                User = r.User,
                UserName = r.User.Name,//string.Format("{0} {1}", r.User.SurName, r.User.Name),
                TitleReviews = r.TitleReviews,
                BodyReviews = r.BodyReviews,
                Like = r.Like,
                Dislike = r.Dislike,
                Date = r.DateReviews
            }).ToList();

            var _user = new User();

            if (User.Identity.IsAuthenticated)
            {
                _user = await _userManager.FindByNameAsync(User.Identity.Name);
            }

            foreach (var item in obj)
            {
                if (item.User == _user)
                    item.AbilityToDeleteAndEdit = true;

                else
                    item.AbilityToDeleteAndEdit = false;

                if (string.IsNullOrEmpty(item.UserName))
                    item.UserName = "Неизвестный";
            }

            return View(obj);
        }

        [Authorize]
        public IActionResult AddReviews()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddReviews(ReviewsViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = new User();

            if (User.Identity.IsAuthenticated)
            {
                user = await _userManager.FindByNameAsync(User.Identity.Name);
            }

            Reviews reviews = new Reviews();
            reviews.User = user;
            reviews.UserId = user.Id;
            reviews.TitleReviews = model.TitleReviews;
            reviews.BodyReviews = model.BodyReviews;
            reviews.DateReviews = DateTime.Now;

            _reviews.AddReviews(reviews);

            return RedirectToAction("Index");
        }

        public IActionResult DeleteReviews(int idReviews)
        {
            _reviews.RemoveReviews(idReviews);
            return RedirectToAction("Index");
        }
    }
}

book-site/Views/Shared/Partial/BookPreview.cshtml
@model book_site.Data.Models.Book

    <div class="preview">
        <div class="content-top-popular-content">
            <a href="~/Home/BookId/@Model.Id"><img src="~/@Model.Img" alt="Book"></a>
            <div class="content-top-popular-letters">
                <p>@Model.Mark</p>
            </div>
        </div>
        <div class="preview-info">
            <div class="price">@Model.Price р.</div>
            <div class="name-book"><a asp-controller="Catalog" asp-action="Search" asp-route-search="@Model.NameBook">@Model.NameBook</a></div>
            <div class="author"><a asp-controller="Catalog" asp-action="Search" asp-route-search="@Model.Author.NameAuthor">@Model.Author.NameAuthor</a></div>
        </div>
    </div>

book-site/Views/Shared/Partial/Footer.cshtml
<footer>
    <div class="map">
        <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A71c8cc6305209e0c8f8a5939685459527f4680e5fe7bb8cda922181511e000e5&amp;width=100%&amp;height=400&amp;lang=ru_RU&amp;scroll=true"></script>
    </div>
</footer>

book-site/Views/Shared/Partial/Header.cshtml
<div class="header-top">
    <p>Мир книг</p>
</div>
<nav class="first-menu">
    <div class="first-menu-left">
        <a class="slogan" href="~/Home/Index">
            <span>Официальный магазин книг г. Подольск</span>
        </a>
        <a class="first-menu-content" asp-controller="Home" asp-action="AboutUs">
            <span>О нас</span>
        </a>
        <a class="first-menu-content" asp-controller="Home" asp-action="Pay">
            <span>Доставка и оплата</span>
        </a>
        <a class="first-menu-content" asp-controller="Home" asp-action="Wholesale">
            <span>Оптовым клиентам</span>
        </a>
        <a class="first-menu-content" asp-controller="Home" asp-action="Loyalty">
            <span>Программа лояльности</span>
        </a>
    </div>
    <div class="first-menu-right">
        <a class="first-menu-right-content" href="tel:+79060612448">
            <span>8 (906) 061-24-48</span>
        </a>
        <a class="first-menu-right-content" href="#">
            <span>Контакты</span>
        </a>
    </div>
</nav>
<div class="stock">
    <a href="#"><img src="~/img/stock.jpg" alt="Баннер/Акция" title="Банер/Акция"></a>
</div>
<div class="header-middle">
    <form asp-controller="Catalog" asp-action="Search" method="get" class="search">
        <a asp-controller="Home" asp-action="Index"><img src="~/img/logo.jpg" alt="Логотип" title="logo"></a>
        <input type="text" name="search" placeholder="Введите название книги, имя автора, жанр">
        <input type="submit" value="Найти">
    </form>
    <div class="header-middle-right-content">
        @await Component.InvokeAsync("UserInfoComponent")
        @await Component.InvokeAsync("BasketComponent")
    </div>
</div>
<div class="header-navigation">
    <nav class="catalog">
        <a href="~/Catalog">Каталог</a>
        <a href="~/Catalog/Books/Stock">Акции</a>
        <a href="~/Catalog/Books/New">Новинки</a>
        <a href="~/Catalog/Books/Favorite">Бестселлеры</a>
        <a asp-controller="Home" asp-action="Error404">Подборки</a>
        <a asp-controller="Home" asp-action="Error404">Рекомендации</a>
        <a asp-controller="Catalog" asp-action="AuthorsList">Авторы</a>
        <a asp-controller="Reviews" asp-action="Index">Отзывы</a>
    </nav>
    <hr>
</div>