book-site/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using book_site.Data.Models;
using book_site.Data;
using book_site.Areas.Admin.ViewModel;
using book_site.Data.Interfaces;
using System.Net;
using OfficeOpenXml;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;

namespace book_site.Areas.Admin.Controllers
{
    [Area(Role.Admin), Authorize(Roles = Role.Admin)]
    public class HomeController : Controller
    {
        private readonly AppDBContent _appDBContent;
        private readonly IBooks _books;
        private readonly IBooksAuthor _author;
        private readonly IBooksGenre _genre;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public HomeController(AppDBContent appDBContent, IBooks books, IBooksAuthor author, IBooksGenre genre, IWebHostEnvironment webHostEnvironment)
        {
            _appDBContent = appDBContent;
            _books = books;
            _author = author;
            _genre = genre;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult LoadEksmo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult LoadEksmo(FileViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            else
            {
                ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
                List<Author> authors = new List<Author>();
                List<Book> books = new List<Book>();
                string fileName = "wwwroot/file/" + UpLoadFile(model.FileName);

                using (ExcelPackage excelPackage = new ExcelPackage(new FileInfo(fileName)))
                {
                    ExcelWorksheet sheet = excelPackage.Workbook.Worksheets[0];
                    for (int i = 18; i <= sheet.Dimension.Rows; i++)
                    {
                        authors.Add(new Author()
                        {
                            NameAuthor = sheet.Cells[i, 7].Value.ToString(),
                            NormalizedNameAuthor = sheet.Cells[i, 7].Value.ToString().ToUpper()
                        });
                    }

                    int index = 0;
                    authors.Sort(Compare);
                    while (index < authors.Count - 1)
                    {
                        if (authors[index].NormalizedNameAuthor == authors[index + 1].NormalizedNameAuthor)
                            authors.RemoveAt(index);
                        else
                        {
                            if (!_author.AllAuthors.Any(a => a.NormalizedNameAuthor == authors[index].NormalizedNameAuthor))
                            {
                                _author.AddAuthor(authors[index].NameAuthor);
                            }
                            index++;
                        }
                    }
                    for (int i = 18; i <= sheet.Dimension.Rows; i++)
                    {
                        Console.Write(i + " ");
                        string filter = sheet.Cells[i, 14].Value.ToString();
                        if (filter.Contains("Книга") || filter.Contains("Комплект"))
                        {
                            double test = 0;
                            int test_2 = 0;
                            if (filter.Contains("Комплект"))
                            {
                                test = Double.Parse(sheet.Cells[i, 5].Value.ToString()) * 0.85 + 500;
                                test = Math.Round(test);
                                test_2 = Int32.Parse(test.ToString());
                            }

                            else
                            {
                                test = Double.Parse(sheet.Cells[i, 5].Value.ToString()) * 0.85 + 200;
                                test = Math.Round(test);
                                test_2 = Int32.Parse(test.ToString());
                            }

                            string url = sheet.Cells[i, 9].Value.ToString();
                            string file = null;
                            using (WebClient client = new WebClient())
                            {
                                file = "../../../../book-site/wwwroot/img/catalog/" + DateTime.Now.DayOfYear + "_" + i + ".jpg";
                                try
                                {
                                    client.DownloadFile(url, file);
                                }
                                catch
                                {
                                    continue;
                                }
                            }

                            books.Add(new Book()
                            {
                                NameBook = sheet.Cells[i, 6].Value.ToString(),
                                NormalizedNameBook = sheet.Cells[i, 6].Value.ToString().ToUpper(),
                                PublishingHouse = "Эксмо",
                                Price = test_2,
                                Img = file
                            });
                        }
                    }
                }
                return View();
            }
        }

        private static int Compare(Author a, Author b)
        {
            return String.Compare(a.NormalizedNameAuthor, b.NormalizedNameAuthor);
        }

        private string UpLoadFile(IFormFile file)
        {
            string fileName = null;
            if (file != null)
            {
                string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "file");
                fileName = file.FileName;
                string filePath = Path.Combine(uploadDir, fileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
            }
            return fileName;
        }
    }
}

book-site/Controllers/HomeController.cs
using book_site.Data.Interfaces;
using book_site.Data.Models;
using book_site.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace book_site.Controllers
{
    public class HomeController : Controller
    {
        private readonly IBooks _books;
        private readonly IBooksGenre _booksGenre;
        private readonly IBooksAuthor _booksAuthor;

        public HomeController(IBooks books, IBooksGenre booksGenre, IBooksAuthor booksAuthor)
        {
            _books = books;
            _booksGenre = booksGenre;
            _booksAuthor = booksAuthor;
        }

        public IActionResult Index()
        {
            ViewBag.Title = "Мир книг | интернет-магазин книг г. Подольска | доставка по Подольску и Москве";
            BooksViewModel obj = new BooksViewModel();
            obj.NewBooks = _books.GetNewBooks;
            obj.StockBooks = _books.GetStockBooks;
            obj.FavoriteBooks = _books.GetFavoriteBooks;
            return View(obj);
        }

        public IActionResult BookId(int id)
        {
            BooksViewModel obj = new BooksViewModel();
            var book = _books.GetBookById(id);
            if (book is null)
                return NotFound();
            else
            {
                obj.BookById = book;
                obj.FavoriteBooks = _books.GetFavoriteBooks;
                return View(obj);
            }
        }

        public IActionResult AboutUs()
        {
            return View();
        }

        public IActionResult Pay()
        {
            return View();
        }
        
        public IActionResult Wholesale()
        {
            return View();
        }

        [Authorize]
        public IActionResult Loyalty()
        {
            return View();
        }

        public IActionResult Error404()
        {
            return View();
        }
    }
}

book-site/Controllers/ShopBasketController.cs
using book_site.Data;
using book_site.Data.Interfaces;
using book_site.Data.Models;
using book_site.Data.Repository;
using book_site.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace book_site.Controllers
{
    [Authorize]
    public class ShopBasketController : Controller
    {
        private readonly IBooks _books;
        private readonly ShopBasket _shopBasket;
        private readonly AppDBContent _appDBContent;

        public ShopBasketController(IBooks books, ShopBasket shopBasket, AppDBContent appDBContent)
        {
            _books = books;
            _shopBasket = shopBasket;
            _appDBContent = appDBContent;
        }

        public ViewResult Basket()
        {
            var items = _shopBasket.GetBookBasket();
            _shopBasket.ListBookBasket = items;
            ShopBasketViewModel obj = new ShopBasketViewModel();
            obj.ShopBasket = _shopBasket;
            return View(obj);
        }

        public IActionResult AddToBasket(int id)
        {
            var item = _books.AllBooks.FirstOrDefault(obj => obj.Id == id);
            if (item != null)
            {
                _shopBasket.AddToBasket(item);
            }
            return RedirectToAction("Basket");
        }

        public IActionResult Plus(int BookId)
        {
            _appDBContent.BookBaskets.Where(bb => bb.BasketBookId == _shopBasket.BasketBookId).FirstOrDefault(b => b.Book.Id == BookId).Counter += 1;
            _appDBContent.SaveChanges();
            return RedirectToAction("Basket");
        }

        public IActionResult Minus(int BookId)
        {
            if (_appDBContent.BookBaskets.Where(bb => bb.BasketBookId == _shopBasket.BasketBookId).FirstOrDefault(b => b.Book.Id == BookId).Counter > 1)
            {
                _appDBContent.BookBaskets.Where(bb => bb.BasketBookId == _shopBasket.BasketBookId).FirstOrDefault(b => b.Book.Id == BookId).Counter -= 1;
                _appDBContent.SaveChanges();
            }
            else
            {
                _appDBContent.BookBaskets.Remove(_appDBContent.BookBaskets.Where(bb => bb.BasketBookId == _shopBasket.BasketBookId).FirstOrDefault(b => b.Book.Id == BookId));
                _appDBContent.SaveChanges();
            }
            return RedirectToAction("Basket");
        }
    }
}

book-site/Views/Home/BookId.cshtml
<div class="way">
    <a href="/">Книги</a>
    <a asp-controller="Catalog" asp-action="Search" asp-route-search="@Model.BookById.Genre.NameGenre">@Model.BookById.Genre.NameGenre</a>
    <a asp-controller="Catalog" asp-action="Search" asp-route-search="@Model.BookById.Author.NameAuthor">@Model.BookById.Author.NameAuthor</a>
    <a asp-controller="Catalog" asp-action="Search" asp-route-search="@Model.BookById.NameBook">@Model.BookById.NameBook</a>
</div>
<div class="preview__product__border">
    <div class="preview__product">
        <div class="picture"><a href="../@Model.BookById.Img"><img src="../@Model.BookById.Img" alt="Внутри убийцы"></a></div>
        <div class="description">
            <div class="description_preview_info">
                Автор: <a asp-controller="Catalog" asp-action="Search" asp-route-search="@Model.BookById.Author.NameAuthor">@Model.BookById.Author.NameAuthor</a><br>
                Издательство: <a href="#">Эксмо, </a>@Model.BookById.Year<div class="br"></div>
                Жанр: <a asp-controller="Catalog" asp-action="Search" asp-route-search="@Model.BookById.Genre.NameGenre">@Model.BookById.Genre.NameGenre</a><br>
                <div class="annotation">
                    <h4>АННОТАЦИЯ</h4>
                    <div class="annotation_content">
                        @Html.Raw(Model.BookById.Annotation)
                    </div>
                </div>
            </div>
            <div class="price">@Model.BookById.Price р.</div>
            <a asp-controller="ShopBasket" asp-action="AddToBasket" asp-route-id="@Model.BookById.Id"><input type="submit" value="Добавить в корзину"></a>
        </div>
    </div>
</div>
<hr>
<div class="content-top-new">
    <div class="new-book-title">
        <div class="new-book">
            <a asp-controller="Catalog" asp-action="Books" asp-route-filter="Favorite">
                <p>Самые покупаемые</p>
            </a>
        </div>
        <div class="new-book-all">
            <a asp-controller="Catalog" asp-action="Books" asp-route-filter="Favorite">
                <p>Все самые покупаемые</p>
            </a>
        </div>
    </div>
    <div class="content-top-popular-all">
        @{
            int i = 0;
            foreach (Book book in Model.FavoriteBooks)
            {
                if (i >= 4)
                    break;
                else
                    @await Html.PartialAsync("Partial/BookPreview", book)
                    i++;
                }
        }
    </div>
</div>
<hr>

book-site/Views/Home/Error404.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="~/css/error404.css" />
</head>
<body>
    <div></div>
    <svg id="svgWrap_2" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" viewBox="0 0 700 250">
        <g>
            <path id="id3_2" d="M195.7 232.67h-37.1V149.7H27.76c-2.64 0-5.1-.5-7.36-1.49-2.27-.99-4.23-2.31-5.88-3.96-1.65-1.65-2.95-3.61-3.89-5.88s-1.42-4.67-1.42-7.22V29.62h36.82v82.98H158.6V29.62h37.1v203.05z" />
            <path id="id2_2" d="M470.69 147.71c0 8.31-1.06 16.17-3.19 23.58-2.12 7.41-5.12 14.28-8.99 20.6-3.87 6.33-8.45 11.99-13.74 16.99-5.29 5-11.07 9.28-17.35 12.81a85.146 85.146 0 0 1-20.04 8.14 83.637 83.637 0 0 1-21.67 2.83H319.3c-7.46 0-14.73-.94-21.81-2.83-7.08-1.89-13.76-4.6-20.04-8.14a88.292 88.292 0 0 1-17.35-12.81c-5.29-5-9.84-10.67-13.66-16.99-3.82-6.32-6.8-13.19-8.92-20.6-2.12-7.41-3.19-15.27-3.19-23.58v-33.13c0-12.46 2.34-23.88 7.01-34.27 4.67-10.38 10.92-19.33 18.76-26.83 7.83-7.5 16.87-13.36 27.12-17.56 10.24-4.2 20.93-6.3 32.07-6.3h66.41c7.36 0 14.58.94 21.67 2.83 7.08 1.89 13.76 4.6 20.04 8.14a88.292 88.292 0 0 1 17.35 12.81c5.29 5 9.86 10.67 13.74 16.99 3.87 6.33 6.87 13.19 8.99 20.6 2.13 7.41 3.19 15.27 3.19 23.58v33.14zm-37.1-33.13c0-7.27-1.32-13.88-3.96-19.82-2.64-5.95-6.16-11.04-10.55-15.29-4.39-4.25-9.46-7.5-15.22-9.77-5.76-2.27-11.8-3.35-18.13-3.26h-66.41c-6.14-.09-12.11.97-17.91 3.19-5.81 2.22-10.95 5.43-15.44 9.63-4.48 4.2-8.07 9.3-10.76 15.29-2.69 6-4.04 12.67-4.04 20.04v33.13c0 7.36 1.32 14.02 3.96 19.97 2.64 5.95 6.18 11.02 10.62 15.22 4.44 4.2 9.56 7.43 15.36 9.7 5.8 2.27 11.87 3.35 18.2 3.26h66.41c7.27 0 13.85-1.2 19.75-3.61s10.93-5.73 15.08-9.98 7.36-9.32 9.63-15.22c2.27-5.9 3.4-12.34 3.4-19.33v-33.15zm-16-26.91a17.89 17.89 0 0 1 2.83 6.73c.47 2.41.47 4.77 0 7.08-.47 2.31-1.39 4.48-2.76 6.51-1.37 2.03-3.14 3.75-5.31 5.17l-99.4 66.41c-1.61 1.23-3.26 2.08-4.96 2.55-1.7.47-3.45.71-5.24.71-3.02 0-5.9-.71-8.64-2.12-2.74-1.42-4.96-3.44-6.66-6.09a17.89 17.89 0 0 1-2.83-6.73c-.47-2.41-.5-4.77-.07-7.08.43-2.31 1.3-4.48 2.62-6.51 1.32-2.03 3.07-3.75 5.24-5.17l99.69-66.41a17.89 17.89 0 0 1 6.73-2.83c2.41-.47 4.77-.47 7.08 0 2.31.47 4.48 1.37 6.51 2.69 2.03 1.32 3.75 3.02 5.17 5.09z" />
            <path id="id1_2" d="M688.33 232.67h-37.1V149.7H520.39c-2.64 0-5.1-.5-7.36-1.49-2.27-.99-4.23-2.31-5.88-3.96-1.65-1.65-2.95-3.61-3.89-5.88s-1.42-4.67-1.42-7.22V29.62h36.82v82.98h112.57V29.62h37.1v203.05z" />
        </g>
    </svg>
    <svg id="svgWrap_1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" viewBox="0 0 700 250">
        <g>
            <path id="id3_1" d="M195.7 232.67h-37.1V149.7H27.76c-2.64 0-5.1-.5-7.36-1.49-2.27-.99-4.23-2.31-5.88-3.96-1.65-1.65-2.95-3.61-3.89-5.88s-1.42-4.67-1.42-7.22V29.62h36.82v82.98H158.6V29.62h37.1v203.05z" />
            <path id="id2_1" d="M470.69 147.71c0 8.31-1.06 16.17-3.19 23.58-2.12 7.41-5.12 14.28-8.99 20.6-3.87 6.33-8.45 11.99-13.74 16.99-5.29 5-11.07 9.28-17.35 12.81a85.146 85.146 0 0 1-20.04 8.14 83.637 83.637 0 0 1-21.67 2.83H319.3c-7.46 0-14.73-.94-21.81-2.83-7.08-1.89-13.76-4.6-20.04-8.14a88.292 88.292 0 0 1-17.35-12.81c-5.29-5-9.84-10.67-13.66-16.99-3.82-6.32-6.8-13.19-8.92-20.6-2.12-7.41-3.19-15.27-3.19-23.58v-33.13c0-12.46 2.34-23.88 7.01-34.27 4.67-10.38 10.92-19.33 18.76-26.83 7.83-7.5 16.87-13.36 27.12-17.56 10.24-4.2 20.93-6.3 32.07-6.3h66.41c7.36 0 14.58.94 21.67 2.83 7.08 1.89 13.76 4.6 20.04 8.14a88.292 88.292 0 0 1 17.35 12.81c5.29 5 9.86 10.67 13.74 16.99 3.87 6.33 6.87 13.19 8.99 20.6 2.13 7.41 3.19 15.27 3.19 23.58v33.14zm-37.1-33.13c0-7.27-1.32-13.88-3.96-19.82-2.64-5.95-6.16-11.04-10.55-15.29-4.39-4.25-9.46-7.5-15.22-9.77-5.76-2.27-11.8-3.35-18.13-3.26h-66.41c-6.14-.09-12.11.97-17.91 3.19-5.81 2.22-10.95 5.43-15.44 9.63-4.48 4.2-8.07 9.3-10.76 15.29-2.69 6-4.04 12.67-4.04 20.04v33.13c0 7.36 1.32 14.02 3.96 19.97 2.64 5.95 6.18 11.02 10.62 15.22 4.44 4.2 9.56 7.43 15.36 9.7 5.8 2.27 11.87 3.35 18.2 3.26h66.41c7.27 0 13.85-1.2 19.75-3.61s10.93-5.73 15.08-9.98 7.36-9.32 9.63-15.22c2.27-5.9 3.4-12.34 3.4-19.33v-33.15zm-16-26.91a17.89 17.89 0 0 1 2.83 6.73c.47 2.41.47 4.77 0 7.08-.47 2.31-1.39 4.48-2.76 6.51-1.37 2.03-3.14 3.75-5.31 5.17l-99.4 66.41c-1.61 1.23-3.26 2.08-4.96 2.55-1.7.47-3.45.71-5.24.71-3.02 0-5.9-.71-8.64-2.12-2.74-1.42-4.96-3.44-6.66-6.09a17.89 17.89 0 0 1-2.83-6.73c-.47-2.41-.5-4.77-.07-7.08.43-2.31 1.3-4.48 2.62-6.51 1.32-2.03 3.07-3.75 5.24-5.17l99.69-66.41a17.89 17.89 0 0 1 6.73-2.83c2.41-.47 4.77-.47 7.08 0 2.31.47 4.48 1.37 6.51 2.69 2.03 1.32 3.75 3.02 5.17 5.09z" />
            <path id="id1_1" d="M688.33 232.67h-37.1V149.7H520.39c-2.64 0-5.1-.5-7.36-1.49-2.27-.99-4.23-2.31-5.88-3.96-1.65-1.65-2.95-3.61-3.89-5.88s-1.42-4.67-1.42-7.22V29.62h36.82v82.98h112.57V29.62h37.1v203.05z" />
        </g>
    </svg>

    <svg>
        <defs>
            <filter id="glow">
                <fegaussianblur class="blur" result="coloredBlur" stddeviation="4"></fegaussianblur>
                <femerge>
                    <femergenode in="coloredBlur"></femergenode>
                    <femergenode in="SourceGraphic"></femergenode>
                </femerge>
            </filter>
        </defs>
    </svg>

    <h2>Страница находится в разработке</h2>
</body>
</html>

book-site/Views/Home/Index.cshtml
@using  book_site.Data.Models

    <div class="content-top-new">
        <div class="new-book-title">
            <div class="new-book">
                <a href="~/Catalog/Books/New">
                    <p>Новинки</p>
                </a>
            </div>
            <div class="new-book-all">
                <a href="~/Catalog/Books/New">
                    <p>Все новинки</p>
                </a>
            </div>
        </div>
        <div class="content-top-new-all">
            @{
                int i = 0;
                foreach (Book book in Model.NewBooks)
                {
                    if (i >= 4)
                        break;
                    else
                        @await Html.PartialAsync("Partial/BookPreview", book)
                    i++;
                }
             }
        </div>
    </div>
    <hr>
    <div class="content-top-new">
        <div class="new-book-title">
            <div class="new-book">
                <a href="~/Catalog/Books/Stock">
                    <p>Акции</p>
                </a>
            </div>
            <div class="new-book-all">
                <a href="~/Catalog/Books/Stock">
                    <p>Все акции</p>
                </a>
            </div>
        </div>
        <div class="content-top-discount-all">
            @{
                i = 0;
                foreach (Book book in Model.StockBooks)
                {
                    if (i >= 4)
                        break;
                    else
                        @await Html.PartialAsync("Partial/BookPreview", book)
                    i++;
                }
            }
        </div>
    </div>
    <hr>
    <div class="content-top-new">
        <div class="new-book-title">
            <div class="new-book">
                <a href="~/Catalog/Books/Favorite">
                    <p>Самые покупаемые</p>
                </a>
            </div>
            <div class="new-book-all">
                <a href="~/Catalog/Books/Favorite">
                    <p>Все самые покупаемые</p>
                </a>
            </div>
        </div>
        <div class="content-top-popular-all">
            @{
                i = 0;
                foreach (Book item in Model.FavoriteBooks)
                {
                    if (i >= 4)
                        break;
                    else
                        @await Html.PartialAsync("Partial/BookPreview", item)
                    i++;
                }
            }
        </div>
    </div>
    <hr>

book-site/Views/Home/Loyalty.cshtml
<h3>Программа лояльности</h3>
<div class="row" style="margin-left: -9px; margin-right: -10px; color: rgb(50, 53, 62); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px; font-weight: 400;"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="padding-left: 12px; padding-right: 13px; width: 995px; text-align: center;"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="padding-left: 12px; padding-right: 13px; width: 970px; padding-top: 20px;"><p style="margin-bottom: 24px; color: rgb(50, 53, 62); font-size: 14px;"><strong><span style="cursor: pointer; transition-duration: 0.15s; transition-timing-function: ease-out; transition-property: color; border-style: initial; border-color: initial; border-image: initial; outline-color: initial; outline-style: initial; line-height: inherit;"><u>Золотая накопительная карта</u></span></strong></p><p style="margin-bottom: 24px; color: rgb(50, 53, 62); font-size: 14px;"><strong><a href="https://www.moscowbooks.ru/pages/bookbank/" target="_blank" style="cursor: pointer; transition: color 0.15s ease-out 0s; text-decoration-line: underline; color: rgb(50, 53, 62); border: 0px; outline: 0px; line-height: inherit;"><img alt="" src="https://www.moscowbooks.ru/image/gallery/b/2017121020135122656.png" style="margin-bottom: 20px; display: block; margin-left: 10px; margin-right: 10px; float: left; width: 250px; height: 214px;"></a></strong></p><p style="margin-bottom: 24px; color: rgb(50, 53, 62); font-size: 14px; text-align: start;">— Накапливайте 5% от суммы покупок в виде бонусов;<br>— Оплачивайте бонусными баллами до 50% от суммы покупки в магазине;<br>— Получайте увеличенные бонусы в День рождения и в течение недели после него;<br>— Участвуйте в специальных акциях для владельцев карт книжного магазина «Москва».</p></div></div></div>